name: Docker Build/Push

on:
  push:
    branches: [ contrariamente ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run prod

    - name: Docker login
      uses: docker/login-action@v1.5.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Docker build
      run: docker build . --file contrib/docker/Dockerfile.apache --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.APP_NAME }}

    - name: Docker push
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.APP_NAME }}
